### ISSUE TITLE
test :  주문관련 서비스 테스트코드 작성

### ISSUE THREAD

**Issue by siontext** [uglyMarket/Client-backend#10]
## 내용
* 적용 페이지 : 없음
* 기능 : 주문관련 서비스단 테스트 코드 작성

## TODO
- [x] 주문 생성 테스트
- [x] 사용자가 후기를 작성할 수 있는 주문 목록 조회 테스트
- [x] 사용자가 후기를 작성한 주문 목록 조회 테스트
