### ISSUE TITLE
test : 후기관련 서비스 테스트코드 작성

### ISSUE THREAD

**Issue by siontext** [uglyMarket/Client-backend#11]
## 내용
* 적용 페이지 : 없음
* 기능 : 후기관련 서비스단 테스트 코드 작성

## TODO
- [x] 후기 등록 테스트
- [x] 후기 삭제 테스트
- [x] 특정 후기 조회 테스트
- [x] 특정 상품의 전체 후기 목록 조회 테스트
