### ISSUE TITLE
refactor : SOLID 원칙에 알맞은 코드 리팩터링

### ISSUE THREAD

**Issue by siontext** [uglyMarket/Client-backend#17]
## 적용 페이지
* 모든 페이지

## 기능
* SOLID 원칙에 맞추어 코드를 수정합니다.

## TODO
- [x] order 도메인 SOLID 원칙에 알맞게 수정
- [x] member 도메인 SOLID 원칙에 알맞게 수정 
- [x] products 도메인 SOLID 원칙에 알맞게 수정 
- [x] 유저, 주문, 상품, 리뷰 찾기 메서드에 제어의 역전, 개방폐쇄 원칙 수정
