### ISSUE TITLE
CICD와 무중단배포 구축

### ISSUE THREAD

**Issue by siontext** [uglyMarket/Client-backend#24]
## 적용 페이지
* 없음

## 기능
* server health-check 기능
*  CI 단계: 코드 변경사항이 지속적으로 통합되어 자동으로 빌드되고 테스트 되도록 함
* CD 단계: CI 단계 이후, 코드가 자동으로 master 환경에 배포

## TODO
- [x] server health-check 기능 추가
- [x] healthCheck를 위한 설정파일과 docker파일 생성
- [x] CICD.yml 파일생성
- [x] uglymarket 전용 서버 DB 생성
