### ISSUE TITLE
test : 테스트 코드 작성

### ISSUE THREAD

**Issue by siontext** [uglyMarket/Client-backend#30]
## 적용 페이지
* 없음

## 기능
* 테스트 코드 작성
* 테스트 커버리지 80% 목표

## TODO
- [x] user 서비스 테스트코드 작성
- [x] user 컨트롤러 테스트코드 작성
- [x] order 서비스 테스트코드 작성
- [x] order 컨트롤러 테스트코드 작성
- [x] review 서비스 테스트코드 작성
- [x] review 컨트롤러 테스트코드 작성
- [x] product 서비스 테스트코드 작성
