### ISSUE TITLE
refactor : pojo를 준수하는 클래스와 아키텍처 활용 및 개발

### ISSUE THREAD

**Issue by siontext** [uglyMarket/Client-backend#53]
## 적용 페이지
* 모든 페이지

## 기능
* 비즈니스 로직과 엔티티 간의 분리, 약한 결합 유지 등을 고려하여 재설계 하였음
* 도메인 계층과 서비스 계층을 나누어 명확하게 역할을 분리함
* 도메인 계층에서 핵심 비즈니스 로직을 처리하도록 만듬
* 도메인 계층을 POJO로 작성하여 프레임워크가 바뀌더라도 
핵심 비즈니스 로직에 영향이 없도록 만듬
* 컨트롤러, 서비스, 매퍼, 팩토리, 도메인 등 각 계층이 명확하게 분리되었음

## TODO
- [x] pojo를 준수하는 user-domain 클래스와 아키텍처 활용 및 개발
- [x] pojo를 준수하는 orders-domain 클래스와 아키텍처 활용 및 개발
- [x] pojo를 준수하는 review-domain 클래스와 아키텍처 활용 및 개발
- [x] pojo를 준수하는 product-domain 클래스와 아키텍처 활용 및 개발
